### ISSUE TITLE
Renaming Files

### ISSUE THREAD

**Issue by christoffwalker** [stvnthomas/CodeIgniter-Multi-Upload#3]
Hi Steven, 

Many thanks for your library!
So far it's working great, until I come to try and rename the files.
(I need to do so in order to write each file to a db).

Using your example, 

```
$this->upload->initialize(array(
        "file_name"     => array("file_1.ext", "file_2.ext", "file_3.ext")
));
```

I've written an array which renames each file with it's correct file extension:

```
// Filenames array
$i = 0;
foreach($_FILES['files']['name'] as $k => $v) {

    // Get the file extension
    $file_ext = explode('.', $v);

    // Write the new filename
    if($i > 0) $filenames_ar .= ', "img_'.$i.'.'.$file_ext[1].'"';
    else $filenames_ar .= '"img_'.$i.'.'.$file_ext[1].'"';
    $i++ ;
}
```

So i get the following for $filenames_ar:

```
"img_0.jpg", "img_1.png"
```

And use it as follows:

```
$this->upload->initialize(array(
        "file_name"     => array($filenames_ar)
));
```

However, I get the error:
"The filetype you are attempting to upload is not allowed".

I've tried to populate the "file_type" in the same way but it returns the same error...

Any ideas?

Many Thanks!
Chris

**Comment by christoffwalker** [comment]
Here's my full initialize array,

```
$this->upload->initialize(array(
            "upload_path"   => FCPATH.'assets/images/uploaded/',
            "file_name"     => array($filenames_ar),
            "allowed_types" => 'jpg|png',
            "max_size"      => '5000'
));
```

**Comment by stvnthomas** [comment]
_file_name_ should be an array rather than a string. If you change your code to this it should work:

```
// Filenames array
$filenames_ar = array();
$i = 0;
foreach($_FILES['file']['name'] as $k => $v) {

    // Get the file extension
    $file_ext = explode('.', $v);

    // Write the new filename
    $filenames_ar[$k] = "img_{$i}.{$file_ext[1]}";
    $i++;
}
```

Another common reason for a file type error is an incorrectly parsed name and extension. For example, if you upload a file with the name _i.will.error.jpg_ using the above block of code, you'll get a filename _i.will_ because it only takes into account the first occurrence of a period character. You can use [pathinfo()](http://php.net/manual/en/function.pathinfo.php) for more reliable filename parsing or a sligntly modified version of what you already have:

```
//Filename.
$segments           = explode(".", $v);
$extension          = array_pop($segments);
$name               = "img_{$i}.{$extension}";
$filenames_ar[$key] = "{$name}.{$extension}";
```

**Comment by christoffwalker** [comment]
Superb... Thank you very much Steven!
Works a treat...

**Comment by stvnthomas** [comment]
No prob.
